##############################################################################################
#
# Travis CI configuration file
# 
# Set the required secrets in the build settings of the project:
#   - BINTRAY_USER
#   - BINTRAY_API_KEY
#
##############################################################################################
env:
  global:
  - PACKAGE_NAME=rpm-builder-bintray
  - PACKAGE_DESC="Builder tool to create .rpm packages (using Travis) and upload to Bintray"
  - BINTRAY_REPO_NAME=rpm
  - BINTRAY_LICENSE=LGPL-2.1

addons:
  apt:
    packages:
    - rpm

before_install:
  # Export variables containing versions and filename
  - export SOFTWARE_VERSION=$(cat VERSION)
  - export RELEASE_VERSION=$TRAVIS_BUILD_NUMBER
  - export BUILD_VERSION=$SOFTWARE_VERSION.$RELEASE_VERSION
  - export BUILD_DATE=$(date "+%Y%m%d")
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME-$BUILD_VERSION.rpm

script:
  # Replace version and build number with the RPM .spec file
  - sed -i "s/__NAME__/$PACKAGE_NAME/g" $PACKAGE_NAME/*.spec
  - sed -i "s/__DESC__/$PACKAGE_DESC/g" $PACKAGE_NAME/*.spec
  - sed -i "s/__LICENSE__/$BINTRAY_LICENSE/g" $PACKAGE_NAME/*.spec
  - sed -i "s/__SOFTWARE_VERSION__/$SOFTWARE_VERSION/g" $PACKAGE_NAME/*.spec
  - sed -i "s/__RELEASE_VERSION__/$RELEASE_VERSION/g" $PACKAGE_NAME/*.spec
  - sed -i "s/__DATE__/$BUILD_DATE/g" $PACKAGE_NAME/*.spec
  # Create the RPM package
  - cat $PACKAGE_NAME/rpm.spec
  - cd $PACKAGE_NAME
  - rpmbuild -v -bb --target x86_64 rpm.spec

after_success:
  # Output detail on the resulting package for debugging purpose
  - ls -laths .
  #- md5sum *
  #- sha256sum *
  #- export LOCAL_SHA256=$( sha256sum $PACKAGE_NAME_VERSION | cut -d " " -f1 )

before_deploy:
  # Set the packages name and details in the descriptor file
  - sed -i "s/__NAME__/$PACKAGE_NAME/g" bintray-descriptor.json
  - sed -i "s/__REPO_NAME__/$BINTRAY_REPO_NAME/g" bintray-descriptor.json
  - sed -i "s/__SUBJECT__/$BINTRAY_USER/g" bintray-descriptor.json
  - sed -i "s/__LICENSE__/$BINTRAY_LICENSE/g" bintray-descriptor.json
  - sed -i "s/__VERSION__/$BUILD_VERSION/g" bintray-descriptor.json

deploy:
  # Upload RPM packages to Bintray
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true

after_deploy:
  # Add time delay to let the servers process the uploaded files
  - sleep 180
  # Retrieve SHA256 sum and compare with local sum to ensure correct file uploaded
  - export REMOTE_SHA256=$(curl -L -v --silent https://bintray.com/$BINTRAY_USER/$BINTRAY_REPO_NAME/download_file?file_path=Packages.gz | zcat | grep -A 3 $PACKAGE_NAME_VERSION | grep SHA256 | cut -d " " -f2)
  - echo "REMOTE_SHA256: $REMOTE_SHA256"
  - >
    if [[ "$LOCAL_SHA256" != "$REMOTE_SHA256" ]]; then
      echo "SHA256 sums don't match: $LOCAL_SHA256 vs $REMOTE_SHA256"
      travis_terminate 1;
    fi
  # Place link to the file in download list
  - |
    curl --silent --show-error --fail\
    -X PUT -H "Content-Type: application/json" -d'{"list_in_downloads": true}'\
    -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/file_metadata/$BINTRAY_USER/$BINTRAY_REPO_NAME/$PACKAGE_NAME_VERSION
